services:
  anthracite-web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./default_www/docker_compose/
        target: /www 
      - type: bind
        source: ./build_supp/default_config.cfg
        target: /anthracite.cfg
